from pydantic import BaseModel, Field, validator
from typing import List
from datetime import datetime

class PriceItem(BaseModel):
    name:str=Field(...,min_length=1,max_length=200,description="Item name")
    price:float=Field(...,gt=0,description="Item Price (must be positive)")

    @validator('price')
    def round_price(cls,v):
        return round(v,2)


class PDFRequest(BaseModel):
    title:str=Field(...,min_length=1,max_length=200,description="Document title")
    date:str=Field(...,description="Date in YYYY-MM-DD format")
    items: List[PriceItem] = Field(..., min_items=1, description="List of price items")
    footer_text: str = Field(
        default="Generated by Appropriate Tech Solutions",
        max_length=500,
        description="Footer text for the PDF"
    )
    @validator('date')
    def validate_date_format(cls, v):
        """Validate date format"""
        try:
            datetime.strptime(v, '%Y-%m-%d')
            return v
        except ValueError:
            raise ValueError('Date must be in YYYY-MM-DD format')
    
    class Config:
        schema_extra = {
            "example": {
                "title": "Price List",
                "date": "2025-02-10",
                "items": [
                    {"name": "Item A", "price": 120},
                    {"name": "Item B", "price": 150}
                ],
                "footer_text": "Generated by Appropriate Tech Solutions"
            }
        }
